[package]
name = "QUEUE_TEST"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
ordered-float = "4.2.2"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.209", features = ["derive"] }

[[bin]]
name = "QUEUE_TEST"
path = "src/main.rs"
