[package]
name = "QUEUE_TEST"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.4"
array-macro = "2.1.8"
crossbeam = "0.8.4"
crossbeam-queue = "0.3.11"
csv = "1.3.0"
ordered-float = "4.2.2"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.209", features = ["derive"] }
flamegraph = "0.6.7"

[[bin]]
name = "QUEUE_TEST"
path = "src/main.rs"

[profile.release]
<<<<<<< Updated upstream
debug = true
=======
debug = true
>>>>>>> Stashed changes
